name = "Create n' Chill"
author = "Ricky12Awesome"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6b5af94e8d2c8d0345730990c91bb04587f45cf67d4dc15f386e0e971c86fa0"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
