name = "Create n' Chill"
author = "Ricky12Awesome"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9f65337d1b2c53f20d63d29db93f4e5d5b33945031b4a603060ec573d9821a8"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
override-side-default = true
