name = "Create n' Chill"
author = "Ricky12Awesome"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cd860a23158257b2935b0fdac023d407072b47f29354cddfbfe0d39cc6dc0ea"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
override-side-default = true
