name = "Create n' Chill"
author = "Ricky12Awesome"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0453091a10f0e0cb4c7eb07be0b6cebe78397b8c9c05dd2ad7b581c3ad7e173b"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
